# Generated by Django 5.2.10 on 2026-01-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Внешний ID'),
            preserve_default=False,
        ),
    ]
